version: "3.7"

services:
  postgres:
    image: postgres:latest
    networks:
      - simplenet
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./data:/data
    ports :
      - 6432:6432
    environment:
      - POSTGRES_PASSWORD=sawa11
      - POSTGRES_USER=coba1
      - POSTGRES_DB=DbStore

  redis:
    image: redis:latest
    command: redis-server --requirepass ' passwordnyaapa'
    networks:
      - simplenet
    volumes:
      - ./redis:/data

  nodejs:
    image: silverstack19/backend:latest
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs:/backend/logs
    ports:
      - 1999:1999
    networks:
      - simplenet
    environment:
      - DB_USER=coba1
      - DB_HOST=postgres
      - DB_DATABASE=DbStore
      - DB_PASS=sawa11
      - SERVICEPORT= 1999
      - JWT_KEYS= mantap
      - REDIS_HOST=redis
      - REDIS_PASSWORD= passwordnyaapa
      - REDIS_PORT= 6379

networks:
  simplenet:
